version: '3'
# docker-compose up
services:
  web:
    container_name: secondsite
    image: wilfongjt/secondsite
    build:
      context: ./secondsite-web/
    command: >
      bash -c "npm install && npm run dev"
    volumes:
      - ./secondsite-web:/usr/src
    ports:
      - "3000:3000"
